ALTER TABLE "Favorite"
ADD COLUMN "windAlertEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "windAlertMinKmh" DOUBLE PRECISION,
ADD COLUMN "windAlertMaxKmh" DOUBLE PRECISION;

ALTER TABLE "StationFavorite"
ADD COLUMN "windAlertEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "windAlertMinKmh" DOUBLE PRECISION,
ADD COLUMN "windAlertMaxKmh" DOUBLE PRECISION;
