name: Feature Request
description: Proposer une nouvelle fonctionnalité
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Merci de proposer une amélioration !
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Décris la fonctionnalité souhaitée
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Pourquoi cette feature serait utile ?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
      description: As-tu envisagé d'autres approches ?
  - type: textarea
    id: context
    attributes:
      label: Contexte additionnel
      description: Screenshots, liens, exemples d'autres apps...
